### ISSUE TITLE
Long titles move player options

### ISSUE THREAD

**Issue by NeoAtrum** [ApolloTVofficial/cplayer#10]
Longer movie/episode titles (especially when an episode title indicates the series, season, and episode name) move the three player option icons off of the screen on my cell phone.  I take it to be a screen size issue, rather than a model issue, but I'm using an HTC U11.  While the 3-dot menu button doesn't function at this time, I'm hoping it will eventually have subtitle options.  Not being able to turn on subtitles is going to make some content unwatchable.

**Comment by NBTX** [comment]
This has been fixed in the latest build.
